# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: EightPaws Tech
email: isabellerochecouste@eightpawstech.com
description: >- 
  EightPaws Tech is a Software Consultancy and Development Business
baseurl: "/"
url: "http://www.eightpawstech.com" 
github_username:  Isabelle1510

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-coffeescript


social:
  - title: twitter
    url: https://twitter.com/EightPawsTech
  - title: github
    url: https://github.com/Isabelle1510
  - title: linkedin
    url: https://www.linkedin.com/in/isabelle-rochecouste-924b22119/

offerings:
  - title: Software Development
    description: Whether you need additional man/womanpower on your existing development team or have an adhoc website/tool which you need built. We can deliver high-quality, well-tested, and maintainable code to set your business up for success.
    image_path: ./assets/images/checklist.png
  - title: Software Consultancy
    description: We can assist you with organising your backlog, developing strategic technical roadmaps, improving technical solutions, or help you with hiring your first developers. If you don't know where to start or are stuck in your current situation, let us help you!
    image_path: ./assets/images/settings.png
  - title: Digital Transformation
    description: We can help you get up to speed with the newest technologies by incorporating them into your system for better flexibility and speed. We provide a holistic approach that makes sure all aspects of your organization come together flawlessly.
    image_path: ./assets/images/project-management.png

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
